# This is a basic workflow to help you get started with Actions

name: UploadFilesToServer

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-upload:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Build with Parcel
        uses: actions/setup-node@v2
      - run: npm install
      - run: npx parcel ./src/*.html ./src/*/*.html
      
      - name: Copy via ssh
        # You may pin to the exact commit or the version.
        # uses: garygrossgarten/github-action-scp@dba89d858413133b6e35da91a3c989cc8cde3ad4
        uses: garygrossgarten/github-action-scp@v0.7.3
        with:
          # Path to the local folder you want to copy.
          local: ./dist
          # Path on the remote server to copy to.
          remote: /home/ubuntu/server/museum/website
          # Hostname or IP address of the server.
          host: 62.234.147.251
          # Username for authentication.
          username: ubuntu
          # Password for password-based user authentication.
          password: ${{ secrets.SSH_PASSWORD }}
